ShopThoiTrang/Controllers/CartController.cs
using ShopThoiTrang.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ShopThoiTrang.Controllers
{
    public class CartController : Controller
    {
        ShopThoiTrangDBContext db = new ShopThoiTrangDBContext();
        private const string CartSession = "CartSession";
        // GET: Cart
        public ActionResult Index()
        {
            var cart = Session[CartSession];
            var list = new List<ModelCart>();
            if (cart != null)
            {
                list = (List<ModelCart>)cart;
            }
            return View(list);
        }
        public ActionResult AddItem(int productId, int quantity = 1)
        {
            var cart = Session[CartSession];
            if (cart != null)
            {
                var list = (List<ModelCart>)cart;
                if (list.Exists(m => m.ProductId == productId))
                {

                    foreach (var item in list)
                    {
                        if (item.ProductId == productId)
                        {
                            item.Quantity += quantity;
                        }
                    } 
                }
                else
                {
                    //tao doi tuong cart item
                    var item = new ModelCart();
                    item.ProductId = productId;
                    item.Quantity = quantity;
                    item.Product = db.Product.Find(productId);
                    list.Add(item);
                }
                Session[CartSession] = list;
            }
            else
            {
                //tao doi tuong cart item
                var item = new ModelCart();
                item.ProductId = productId;
                item.Quantity = quantity;
                item.Product = db.Product.Find(productId);
                var list = new List<ModelCart>();

                //gan vao session
                Session[CartSession] = list;
            }
            return RedirectToAction("Index");
        }
        public ActionResult DeleteItem(int productId)
        {
            var cart = Session[CartSession];
            var list = (List<ModelCart>)cart;
            foreach (var item in list)
            {
                if (item.ProductId == productId)
                {
                    list.Remove(item);
                    Session[CartSession] = list;
                    break;
                }
            }
            return RedirectToAction("Index");
        }
      
    }
}

ShopThoiTrang/Controllers/CustomerController.cs
using ShopThoiTrang.Library;
using ShopThoiTrang.Models;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ShopThoiTrang.Controllers
{
    public class CustomerController : Controller
    {
        ShopThoiTrangDBContext db = new ShopThoiTrangDBContext();
        // GET: Customer
        public ActionResult Login()
        {
            if(Session["UserCustomer"].Equals(""))
            {
                ViewBag.Error = "";
                return View();
            }
            return RedirectToAction("Index", "Site");
        }
        [HttpPost]
        public ActionResult Login(FormCollection field)
        {
            string strerror = "";
            string username = field["email"];
            string password = Mystring.ToMD5(field["pass"]);
            ModelUser rowuser = db.Users.Where(m => m.Status == 1 && (m.Phone == username || m.Email == username))
                .FirstOrDefault();
            if (rowuser == null)
            {
                strerror = "Tên đăng nhập không tồn tại!";
            }
            else
            {
                if (rowuser.PassWord.Equals(password))
                {
                    Session["UserCustomer"] = rowuser.UserName;
                    Session["UserId"] = rowuser.Id;
                    Session["FullName"] = rowuser.FullName; 
                    Session["Img"] = rowuser.Img;
                    Session["Email"] = rowuser.Email;
                    Session["Phone"] = rowuser.Phone;
                    return RedirectToAction("Index", "Site");
                }
                else
                {
                    strerror = "Mật khẩu không đúng!";
                }
            }
            ViewBag.Error = "<span class='text-danger'>" + strerror + "</span>";
            return View();
        }
        public ActionResult Logout()
        {
            Session["UserCustomer"] = "";
            Session["UserId"] = "";
            Session["FullName"] = "";
            Session["Img"] = "";
            Session["Email"] = "";
            Session["Phone"] = "";
            return RedirectToAction("Index", "Site");
        }
        public ActionResult Signin()
        {
            return View();
        }

        // POST: Admin/Users/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Signin(ModelUser modelUser)
        {
            string strerror = "";
            if (ModelState.IsValid)
            {
                try
                {
                    var file = Request.Files["img"];
                    if (file == null)
                    {
                        strerror = "Hình Chưa Được Chọn";
                    }
                    else
                    {
                        string[] FileExtentsions = new string[] { ".jpg", ".gif", ".png" };
                        if (!FileExtentsions.Contains(file.FileName.Substring(file.FileName.LastIndexOf('.'))))
                        {
                            strerror = "Kiểu Tập Tin " + string.Join(", ", FileExtentsions) + " Không Cho Phép!";
                        }
                        else
                        {
                            string strName = Mystring.str_slug(modelUser.FullName);
                            String fileName = strName + file.FileName.Substring(file.FileName.LastIndexOf('.'));
                            modelUser.Img = fileName;
                            String Strpath = Path.Combine(Server.MapPath("~/Public/Image/User"), fileName);
                            file.SaveAs(Strpath);
                            string matkhau = Mystring.ToMD5(modelUser.PassWord);
                            modelUser.Status = 1;
                            modelUser.PassWord = matkhau;
                            modelUser.Created_By = 1;
                            modelUser.Created_At = DateTime.Now;
                            modelUser.Update_By = 1;
                            modelUser.Update_At = DateTime.Now;
                            db.Users.Add(modelUser);
                            db.SaveChanges();
                            Session["UserCustomer"] = modelUser.UserName;
                            Session["UserId"] = modelUser.Id;
                            Session["FullName"] = modelUser.FullName;
                            Session["Img"] = modelUser.Img;
                            Session["Email"] = modelUser.Email;
                            Session["Phone"] = modelUser.Phone;
                            return RedirectToAction("Login");
                        }
                    }

                }
                catch (Exception ex)
                {
                    strerror = "Thêm Không Thành Công";
                }

            }
            ViewBag.Error = strerror;
            return View(modelUser);
        }
    }
}

ShopThoiTrang/Controllers/ModuleController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ShopThoiTrang.Models;

namespace ShopThoiTrang.Controllers
{
    public class ModuleController : Controller
    {
        ShopThoiTrangDBContext db = new ShopThoiTrangDBContext();
        // GET: Module
        public ActionResult MainMenu()
        {
            var list = db.Menu.Where(m => m.Status == 1 && m.ParentId == 0
            && m.Position.Equals("top"))
                .OrderByDescending(m => m.Created_At).ToList();
            return View("MainMenu", list);
        }
        public ActionResult SubMainMenu(int id)
        {
            var row_m = db.Menu.Find(id);
            ViewBag.row_m = row_m;
            var list = db.Menu.Where(m => m.Status == 1 && m.ParentId == id);
            if (list.Count()>0)
            {
                //co menu con
                return View("SubMainMenu2", list.ToList());
            }
            else
            {
                //khong co menu con
                return View("SubMainMenu1");
            }
        }
        public ActionResult Slideshow()
        {
            List<ModelSlider> list = db.Slider.Where(m=>m.Status==1 && m.Position.
            Equals("slideshow")).OrderByDescending(m=>m.Created_At).ToList();
            return View("Slideshow", list);
        }
        public ActionResult Banner()
        {
            List<ModelSlider> list = db.Slider.Where(m => m.Status == 1 && m.Position.
            Equals("banner")).OrderByDescending(m => m.Created_At).Take(2).ToList();
            return View("Banner", list);
        }
        public ActionResult ListCategory()
        {
            var list = db.Categories.Where(m => m.Status == 1 && m.ParentId == 0)
               .OrderByDescending(m => m.Created_At).ToList();
            return View("ListCategory", list);
        }
        public ActionResult SubListCategory(int id)
        {
            var row_m = db.Categories.Find(id);
            ViewBag.row_cr = row_m;
            var list = db.Categories.Where(m => m.Status == 1 && m.ParentId == id);
            if (list.Count() > 0)
            {
                //co menu con
                return View("SubListCategory2", list.ToList());
            }
            else
            {
                //khong co menu con
                return View("SubListCategory1");
            }
        }
        public ActionResult listTopic()
        {
            var list = db.Topic.Where(m => m.Status == 1 && m.ParentId == 0)
               .OrderByDescending(m => m.Created_At).ToList();
            return View("listTopic", list);
        }
        public ActionResult SubListTopic(int id)
        {
            var row_t = db.Topic.Find(id);
            ViewBag.row_top = row_t;
            var list = db.Topic.Where(m => m.Status == 1 && m.ParentId == id);
            if (list.Count() > 0)
            {
                //co menu con
                return View("SubListTopic2", list.ToList());
            }
            else
            {
                //khong co menu con
                return View("SubListTopic1");
            }
        }
        public ActionResult ProductBuy()
        {
            var list = db.Product.Where(m => m.Status == 1).OrderByDescending(m => m.Created_At).Take(4).ToList();
            return View("ProductBuy", list );
        }
        public ActionResult FashionNewspaper()
        {
            var list = db.Post
                 .Join(db.Topic,
                 p => p.TopId,
                 t => t.Id,
                 (p, c) => new PostTopic
                 {
                     PostTitle = p.Title,
                     PostImg = p.Img,
                     PostId = p.Id,
                     PostSlug = p.Slug,
                     PostTop = c.Name,
                     PostStatus = p.Status,
                     PostDayCreat = p.Created_At
                 }

                 ).Where(m => m.PostStatus != 0);
            return View("FashionNewspaper", list.ToList());
        }
    }
}

ShopThoiTrang/Views/Shared/LayoutSite.cshtml
<!DOCTYPE html>
<html>
<head>
    <title>@Page.Title</title>
    @*------------------------------- link bootstrap ------------------------------------*@
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" />
    @*------------------------------- link css ------------------------------------*@
    <link href="~/Public/Css/LayoutSite.css" rel="stylesheet" />
    @*------------------------------- link font lato ------------------------------------*@
    <link href="https://fonts.googleapis.com/css2?family=Nosifer&display=swap" rel="stylesheet">
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Barlow+Condensed:ital,wght@1,200&display=swap" rel="stylesheet">

    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Open+Sans+Condensed:wght@300&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Montserrat&family=Open+Sans:wght@700&family=Roboto&display=swap" rel="stylesheet">
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Dancing+Script&display=swap" rel="stylesheet">
    @*font-family: 'Dancing Script', cursive;*@
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Oswald&display=swap" rel="stylesheet">
    @* font-family: 'Oswald', sans-serif;*@
    @*------------------------------- link fontawesome ------------------------------------*@
    <link href="~/Content/font-awesome.css" rel="stylesheet" />
    <link href="~/Content/font-awesome.min.css" rel="stylesheet" />
    <script src="https://kit.fontawesome.com/fd76fb5f52.js" crossorigin="anonymous"></script>
    @*------------------------------- link ckeditor ------------------------------------*@
    <script src="~/Public/ckeditor/ckeditor.js"></script>
    @*------------------------------- link page ------------------------------------*@
    @RenderSection("head", required: false)
</head>
<body>
    <section class="clearfix header bg-white">
        <div class="container">
            <div class="row">
                <div class="col-9 phone text-left">
                    <p> <i class="fa fa-phone"></i> <i>01297493492</i></p>
                </div>
                <div class="col-2 taikhoan">
                    <ul>
                        <li class="tk-cha">
                            <p class="text-center">
                                <i class="fa fa-user"> </i>
                                @if (Session["FullName"].Equals(""))
                                {
                                    <i>Tài Khoản</i>
                                }
                                else
                                {
                                    <i> @Session["FullName"]</i>
                                }

                            </p>
                            <ul class="tk-con">
                                @if (Session["FullName"].Equals(""))
                                {
                                    <li><a href="@Url.Action("Login","Customer")">Đăng Nhập</a></li>
                                    <li><a href="@Url.Action("Signin","Customer")">Đăng Ký</a></li>
                                }
                                else
                                {
                                    <li><a href="@Url.Action("Logout","Customer")">Đăng Xuất</a></li>
                                    <li><a href="@Url.Action("Logout","Customer")">Profile</a></li>
                                }
                            </ul>
                        </li>
                    </ul>
                </div>
                <div class="col-1 giohang text-right">
                    <a href="@Url.Action("Index","Cart")"> <i class="fa fa-shopping-cart"></i> <i>Giỏ Hàng</i></a>
                </div>
            </div>
        </div>
    </section>
    @* **********************************hết header*********************************@
    <section class="clearfix mainmenu ">
        <div class="container">
            @Html.Action("MainMenu", "Module")
        </div>
    </section>
    @* **********************************hết mainmenu*********************************@
    <section class="clearfix content">
        @RenderBody()
    </section>
    @* **********************************hết Content*********************************@
    <section class="clearfix footer">
        <div class="container">
            <div class="footter mt-3">
                <!-- Footer -->
                <footer class="page-footer font-small mdb-color pt-4">

                    <!-- Footer Links -->
                    <div class="container text-center text-md-left">

                        <!-- Footer links -->
                        <div class="row text-center text-md-left mt-3 pb-3">

                            <!-- Grid column -->
                            <div class="col-md-3 col-lg-3 col-xl-3 mx-auto mt-3">
                                <a class="navbar-brand ten-shop" href="#">
                                    <img src="~/Public/Image/logo.png" />
                                </a>
                                <p style="color: 	white;">
                                    Công ty TNHH Công nghệ Tech Việt Nam
                                    Số ĐKKD 999999999 do Sở KHĐT Thành phố Hồ Chí Minh cấp ngày 30/12/2015
                                    Người đại diện: Trưởng Thanh Nguyễn
                                    Địa chỉ: Số 105/562 Đường Lương Định Của, Phường An Phú, Quận 2, TP.HCM
                                </p>
                            </div>
                            <!-- Grid column -->
                            <hr class="w-100 clearfix d-md-none">

                            <!-- Grid column -->
                            <div class="col-md-2 col-lg-2 col-xl-2 mx-auto mt-3">
                                <h6 class="text-uppercase mb-4 font-weight-bold">Danh Mục</h6>
                                <p>
                                    <a href="#!">CÔNG NGHỆ</a>
                                </p>
                                <p>
                                    <a href="#!">THỂ THAO</a>
                                </p>
                                <p>
                                    <a href="#!">ĐIỆN ẢNH</a>
                                </p>
                                <p>
                                    <a href="#!">GAME ONLINE</a>
                                </p>
                            </div>
                            <!-- Grid column -->

                            <hr class="w-100 clearfix d-md-none">

                            <!-- Grid column -->
                            <div class="col-md-3 col-lg-2 col-xl-2 mx-auto mt-3">
                                <h6 class="text-uppercase mb-4 font-weight-bold">Useful links</h6>
                                <p>
                                    <a href="#!">Your Account</a>
                                </p>
                                <p>
                                    <a href="#!">Affiliate</a>
                                </p>
                                <p>
                                    <a href="#!">LIÊN KẾT</a>
                                </p>
                                <p>
                                    <a href="#!">TRỢ GIÚP</a>
                                </p>
                            </div>

                            <!-- Grid column -->
                            <hr class="w-100 clearfix d-md-none">

                            <!-- Grid column -->
                            <div class="col-md-4 col-lg-3 col-xl-3 mx-auto mt-3">
                                <h6 class="text-uppercase mb-4 font-weight-bold">Liên Hệ</h6>
                                <p style="color: 	white;">
                                    <i class="fas fa-home mr-3"></i> 47/7 Khu Phố 2, Quận 2, TPHCM
                                </p>
                                <p style="color: 	white;">
                                    <i class="fas fa-envelope mr-3"></i> truongthanhnguyen2210@gmail.com
                                </p>
                                <p style="color: 	white;">
                                    <i class="fas fa-phone mr-3"></i> + 84 234 567 88
                                </p>
                                <p style="color: 	white;">
                                    <i class="fas fa-print mr-3"></i> + 84 234 567 89
                                </p>
                            </div>
                            <!-- Grid column -->

                        </div>
                        <!-- Footer links -->

                        <hr>

                        <!-- Grid row -->
                        <div class="row d-flex align-items-center">

                            <!-- Grid column -->
                            <div class="col-md-7 col-lg-8">

                                <!--Copyright-->
                                <p class="text-center text-md-left" style="color: white;">
                                    © 2020 Copyright:
                                    <a href="#">
                                        Trưởng Thanh Nguyễn
                                    </a>
                                </p>

                            </div>
                            <!-- Grid column -->
                            <!-- Grid column -->
                            <div class="col-md-5 col-lg-4 ml-lg-0">

                                <!-- Social buttons -->
                                <div class="text-center text-md-right">
                                    <ul class="list-unstyled list-inline">
                                        <li class="list-inline-item">
                                            <a class="btn-floating btn-sm rgba-white-slight mx-1">
                                                <i class="fab fa-facebook-f"></i>
                                            </a>
                                        </li>
                                        <li class="list-inline-item">
                                            <a class="btn-floating btn-sm rgba-white-slight mx-1">
                                                <i class="fab fa-twitter"></i>
                                            </a>
                                        </li>
                                        <li class="list-inline-item">
                                            <a class="btn-floating btn-sm rgba-white-slight mx-1">
                                                <i class="fab fa-google-plus-g"></i>
                                            </a>
                                        </li>
                                        <li class="list-inline-item">
                                            <a class="btn-floating btn-sm rgba-white-slight mx-1">
                                                <i class="fab fa-linkedin-in"></i>
                                            </a>
                                        </li>
                                    </ul>
                                </div>

                            </div>
                            <!-- Grid column -->

                        </div>
                        <!-- Grid row -->

                    </div>
                    <!-- Footer Links -->

                </footer>
                <!-- Footer -->
            </div>
            <!--************************************* hết khối footer  *******************************-->
        </div>
    </section>
    @* **********************************hết footer*********************************@


    <script src="~/Scripts/jquery-3.0.0.slim.js"></script>
    <script src="~/Scripts/popper.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
    @RenderSection("footer", required: false)
</body>
</html>