ShopThoiTrang/Areas/Admin/Controllers/LinksController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ShopThoiTrang.Models;

namespace ShopThoiTrang.Areas.Admin.Controllers
{
    public class LinksController : BaseController
    {
        private ShopThoiTrangDBContext db = new ShopThoiTrangDBContext();

        // GET: Admin/Links
        public ActionResult Index()
        {
            return View(db.Links.ToList());
        }

        // GET: Admin/Links/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ModelLink modelLink = db.Links.Find(id);
            if (modelLink == null)
            {
                return HttpNotFound();
            }
            return View(modelLink);
        }

        // GET: Admin/Links/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Admin/Links/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Name,Slug,Type,TableId")] ModelLink modelLink)
        {
            if (ModelState.IsValid)
            {
                db.Links.Add(modelLink);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(modelLink);
        }

        // GET: Admin/Links/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ModelLink modelLink = db.Links.Find(id);
            if (modelLink == null)
            {
                return HttpNotFound();
            }
            return View(modelLink);
        }

        // POST: Admin/Links/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Name,Slug,Type,TableId")] ModelLink modelLink)
        {
            if (ModelState.IsValid)
            {
                db.Entry(modelLink).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(modelLink);
        }

        // GET: Admin/Links/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ModelLink modelLink = db.Links.Find(id);
            if (modelLink == null)
            {
                return HttpNotFound();
            }
            return View(modelLink);
        }

        // POST: Admin/Links/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            ModelLink modelLink = db.Links.Find(id);
            db.Links.Remove(modelLink);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

ShopThoiTrang/Areas/Admin/Views/Links/Create.cshtml
@model ShopThoiTrang.Models.ModelLink

@{
    ViewBag.Title = "Create";
    Layout = "~/Areas/Admin/Views/Shared/LayoutAdmin.cshtml";
}

<h2>Create</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>ModelLink</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Slug, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Slug, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Slug, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Type, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Type, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Type, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TableId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TableId, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TableId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

ShopThoiTrang/Areas/Admin/Views/Links/Delete.cshtml
@model ShopThoiTrang.Models.ModelLink

@{
    ViewBag.Title = "Delete";
    Layout = "~/Areas/Admin/Views/Shared/LayoutAdmin.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>ModelLink</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Slug)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Slug)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Type)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Type)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TableId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TableId)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

ShopThoiTrang/Areas/Admin/Views/Links/Details.cshtml
@model ShopThoiTrang.Models.ModelLink

@{
    ViewBag.Title = "Details";
    Layout = "~/Areas/Admin/Views/Shared/LayoutAdmin.cshtml";
}

<h2>Details</h2>

<div>
    <h4>ModelLink</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Slug)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Slug)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Type)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Type)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TableId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TableId)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

ShopThoiTrang/Areas/Admin/Views/Links/Edit.cshtml
@model ShopThoiTrang.Models.ModelLink

@{
    ViewBag.Title = "Edit";
    Layout = "~/Areas/Admin/Views/Shared/LayoutAdmin.cshtml";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>ModelLink</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Slug, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Slug, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Slug, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Type, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Type, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Type, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TableId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TableId, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TableId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

ShopThoiTrang/Areas/Admin/Views/Links/Index.cshtml
@model IEnumerable<ShopThoiTrang.Models.ModelLink>

@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/Admin/Views/Shared/LayoutAdmin.cshtml";
}

<div class="card">
    <div class="card-header">
        <div class="row">
            <div class="col-6 text-danger text-uppercase"><strong>Tất cả liên hệ</strong></div>
            <div class="col-6 text-danger text-right">
                <a href="@Url.Action("Create", "Links")" class="btn btn-sm btn-info">Add</a>
                <a href="@Url.Action("Trash", "Links")" class="btn btn-sm btn-danger">Trash</a>
            </div>
        </div>
    </div>
    <div class="card-body">
        <table class="table table-bordered table-hover table-striped">
            <thead>
                <tr class="bg-warning text-uppercase">
                    <th scope="col">Tiêu đề liên hệ </th>
                    <th scope="col">email</th>
                    <th scope="col">điện thoại</th>
                    <th scope="col">trạng thái</th>
                    <th scope="col">Chức Năng </th>
                    <th scope="col">Id</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var row in Model)
                {
                    <tr>
                        <th>@row.Title</th>
                        <td>@row.FullName</td>
                        <td>@row.Email</td>
                        <td>@row.Phone</td>
                        <td>
                            @if (row.Status == 1)
                            {
                                <a href="@Url.Action("Status", "Links", new { id = row.Id })" class="btn btn-sm btn-dark">
                                    <i class="fa fa-toggle-on"></i>
                                </a>
                            }
                            else
                            {
                                <a href="@Url.Action("Status", "Links", new { id = row.Id })" class="btn btn-sm btn-dark">
                                    <i class="fa fa-toggle-off"></i>
                                </a>
                            }

                            <a href="@Url.Action("Edit", "Links", new { id = row.Id })" class="btn btn-sm btn-primary"><i class="fa fa-edit"></i></a>
                            <a href="@Url.Action("Deltrash", "Links", new { id = row.Id })" class="btn btn-sm btn-danger"><i class="fa fa-trash-alt"></i></a>
                        </td>
                        <td>@row.Id</td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>